version: "3.8"

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
     - "8086:8086"
    restart: always
    volumes:
      - /data/influxdb:/var/lib/influxdb 
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/var/lib/redis
